DiSSCo/handle-manager

kubernetes.yaml
src/main/java/eu/dissco/core/handlemanager/controller/HandleController.java

* Kubernetes env
* Remove keycloak

Kubernetes env (#21)

---

src/main/java/eu/dissco/core/handlemanager/component/FdoRecordBuilder.java
src/main/java/eu/dissco/core/handlemanager/controller/HandleController.java
src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
src/test/java/eu/dissco/core/handlemanager/component/FdoRecordBuilderTest.java
src/test/java/eu/dissco/core/handlemanager/service/HandleServiceTest.java

When an update request is made, the FdoRecordBuilder creates a list of HandleAttributes to post to the db.

FdoRecordBuilder prepares update handle attribute list

---

.github/workflows/.trivyignore
Dockerfile
src/main/java/eu/dissco/core/handlemanager/component/PidResolverComponent.java
src/test/java/eu/dissco/core/handlemanager/component/PidResolverComponentTest.java

A method's response is not cached if it is called from within the same class. This has been fixed.

fix caching

---

.github/workflows/.trivyignore
Dockerfile
pom.xml

Alpine has addressed this CVE.

Remove hardcoded openssl version

---

src/main/java/eu/dissco/core/handlemanager/controller/HandleController.java
src/test/java/eu/dissco/core/handlemanager/controller/HandleControllerTest.java

Better logging

---

src/main/java/eu/dissco/core/handlemanager/configuration/WebClientConfig.java
src/main/java/eu/dissco/core/handlemanager/domain/requests/objects/DigitalSpecimenRequest.java
src/main/java/eu/dissco/core/handlemanager/service/FdoRecordService.java
src/main/java/eu/dissco/core/handlemanager/web/PidResolver.java
src/test/java/eu/dissco/core/handlemanager/component/FdoRecordServiceTest.java
src/test/java/eu/dissco/core/handlemanager/component/PidResolverTest.java

Resolve qnumbers for specimenHosts

Qnumber support

---

src/main/java/eu/dissco/core/handlemanager/service/HandleService.java

Dynamic prefix length to allow for `TEST` prefix

Dynamic prefix length

---

src/main/java/eu/dissco/core/handlemanager/service/FdoRecordService.java
src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
src/test/java/eu/dissco/core/handlemanager/service/HandleServiceTest.java

Remove HS admin handle from the JSON response.

Remove admin handle from response

---

src/main/java/eu/dissco/core/handlemanager/domain/requests/vocabulary/TopicDiscipline.java
src/main/java/eu/dissco/core/handlemanager/domain/requests/vocabulary/TopicDomain.java

- capitalize some terms
- allow "unclassified" topicDiscipline

align topic discipline terms

---

src/main/java/eu/dissco/core/handlemanager/service/FdoRecordService.java
src/test/java/eu/dissco/core/handlemanager/testUtils/TestUtils.java

Reordered 10320/loc field so landing page is the default

handle resolves to landing page first

---

src/main/java/eu/dissco/core/handlemanager/domain/FdoProfile.java

change normalised primary specimen object id

---

src/main/java/eu/dissco/core/handlemanager/properties/ProfileProperties.java
src/main/java/eu/dissco/core/handlemanager/service/FdoRecordService.java
src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
src/test/java/eu/dissco/core/handlemanager/service/FdoRecordServiceTest.java
src/test/java/eu/dissco/core/handlemanager/service/HandleServiceTest.java
src/test/java/eu/dissco/core/handlemanager/testUtils/TestUtils.java

Some strings will need to change based on if we're minting DOIs or Handles. This class can be useful in keeping them all together.

Move profile properties to its own class

---

src/main/java/eu/dissco/core/handlemanager/properties/ProfileProperties.java
src/main/java/eu/dissco/core/handlemanager/service/FdoRecordService.java
src/test/java/eu/dissco/core/handlemanager/service/FdoRecordServiceTest.java

FdoRecordService was checking wrong string to verify profile, so the wrong location was being added to the handle record

Hot fix/fix locations

---

src/main/java/eu/dissco/core/handlemanager/domain/FdoProfile.java
src/main/java/eu/dissco/core/handlemanager/domain/requests/objects/MediaObjectRequest.java
src/main/java/eu/dissco/core/handlemanager/service/FdoRecordService.java
src/test/java/eu/dissco/core/handlemanager/service/FdoRecordServiceTest.java
src/test/java/eu/dissco/core/handlemanager/testUtils/TestUtils.java

License is optional
Improve FdoRecordService testing

fix data model testing

---

.github/workflows/.trivyignore
pom.xml
src/main/java/eu/dissco/core/handlemanager/web/PidResolver.java
src/test/java/eu/dissco/core/handlemanager/component/PidResolverTest.java

Recover if external PID isn't resolved

Exception Recovery

---

src/main/java/eu/dissco/core/handlemanager/controller/PidController.java
src/main/java/eu/dissco/core/handlemanager/controller/RestResponseEntityExceptionHandler.java
src/main/java/eu/dissco/core/handlemanager/exceptions/DatabaseCopyException.java
src/main/java/eu/dissco/core/handlemanager/repository/BatchInserter.java
src/main/java/eu/dissco/core/handlemanager/repository/PidRepository.java
src/main/java/eu/dissco/core/handlemanager/service/DoiService.java
src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
src/main/java/eu/dissco/core/handlemanager/service/PidService.java
src/test/java/eu/dissco/core/handlemanager/controller/PidControllerExceptionHandlerTest.java
src/test/java/eu/dissco/core/handlemanager/repository/BatchInserterIT.java

[Jira](https://naturalis.atlassian.net/browse/DD-981?atlOrigin=eyJpIjoiZGVkMWIzZTBlNzdkNGIzYWFhODUzYjAwNjlmNTBkYTMiLCJwIjoiaiJ9)
503 SERVICE UNAVAILABLE for db exceptions

Database Copy Exception

---

src/main/java/eu/dissco/core/handlemanager/service/FdoRecordService.java

This allows for flexibility  in what kind of fields we can update

Map<String, Object> 

---

src/main/java/eu/dissco/core/handlemanager/service/DoiService.java
src/main/java/eu/dissco/core/handlemanager/service/FdoRecordService.java
src/test/java/eu/dissco/core/handlemanager/service/FdoRecordServiceTest.java

Better logging, a quick filter issue, and check for a wikidata id properly

Bug fix/update pid resolution issue

---

src/main/java/eu/dissco/core/handlemanager/service/FdoRecordService.java
src/test/java/eu/dissco/core/handlemanager/service/FdoRecordServiceTest.java

- fixes qid resolution issue
- better logging and cleaner exception handling (removed some redundant exceptions)

resolve wikidata entity

---

src/main/java/eu/dissco/core/handlemanager/HandleManagerApplication.java
src/main/java/eu/dissco/core/handlemanager/configuration/SpringCacheConfig.java
src/main/java/eu/dissco/core/handlemanager/service/CacheEvictionService.java
src/main/java/eu/dissco/core/handlemanager/web/PidResolver.java

CacheManager = holds names of caches (pidname, qid)
CacheEvictionService = every 12 hours, evicts caches in cache manager
Will need to update deployment file with eviction frequency (43200000 ms)

Evict cache every 12 hours

---

src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
src/test/java/eu/dissco/core/handlemanager/controller/PidControllerExceptionHandlerTest.java

Additional logging, sonar issue

capture unresolved handles

---

src/main/java/eu/dissco/core/handlemanager/configuration/KafkaPublisherConfiguration.java
src/main/java/eu/dissco/core/handlemanager/repository/MongoRepository.java
src/main/java/eu/dissco/core/handlemanager/service/DoiService.java
src/main/java/eu/dissco/core/handlemanager/service/PidService.java
src/main/resources/json-schema/mas-request-attributes.json
src/test/java/eu/dissco/core/handlemanager/repository/MongoRepositoryIT.java
src/test/java/eu/dissco/core/handlemanager/testUtils/TestUtils.java

- Returns digitalMediaKey, an object that contains specimenID and url 
- specify local id type so we can choose what kind of indexed id we get from mongo

digital media returns key

---

src/main/java/eu/dissco/core/handlemanager/controller/PidController.java
src/main/java/eu/dissco/core/handlemanager/domain/fdo/FdoProfile.java
src/main/java/eu/dissco/core/handlemanager/domain/fdo/FdoType.java
src/main/java/eu/dissco/core/handlemanager/repository/MongoRepository.java
src/main/java/eu/dissco/core/handlemanager/service/DoiService.java
src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
src/main/java/eu/dissco/core/handlemanager/service/KafkaPublisherService.java
src/main/java/eu/dissco/core/handlemanager/service/PidService.java
src/test/java/eu/dissco/core/handlemanager/controller/PidControllerTest.java
src/test/java/eu/dissco/core/handlemanager/repository/MongoRepositoryIT.java
src/test/java/eu/dissco/core/handlemanager/service/KafkaPublisherServiceTest.java

- Fix bug with updates in fdo record. When retrieving fdo record for updates, we need to fill the map<FdoProfile, FdoAttribute> instead of returning an empty map. 
- Adds `FdoType.fromString()` function
- Logging improvements
- Doesn't fail if requests are empty

ingestion fixes

---

src/main/java/eu/dissco/core/handlemanager/controller/PidController.java
src/main/java/eu/dissco/core/handlemanager/domain/fdo/FdoType.java
src/test/java/eu/dissco/core/handlemanager/controller/PidControllerTest.java

Small PR for some updates needed for production.
Small change to the route so it we can switch the endpoint
Small change in the FDO types to align with https://github.com/DiSSCo/dissco-developers-documentation/wiki/FDO-types-and-profiles

Update for the FDO types and the routes

---

src/main/java/eu/dissco/core/handlemanager/component/PidResolver.java
src/main/java/eu/dissco/core/handlemanager/service/FdoRecordService.java
src/test/java/eu/dissco/core/handlemanager/component/PidResolverTest.java
src/test/java/eu/dissco/core/handlemanager/service/FdoRecordServiceTest.java

- Update wikidata api
- Separate execution and interrupted exceptions on external pid resolution
[Jira](https://naturalis.atlassian.net/browse/DD-1684)

update wikidata to v1

---

pom.xml
src/main/java/eu/dissco/core/handlemanager/domain/repsitoryobjects/FdoAttribute.java
src/main/java/eu/dissco/core/handlemanager/service/DataCiteService.java
src/test/java/eu/dissco/core/handlemanager/service/DataCiteServiceTest.java

Datacite: align with DC model
Fdo Values may also be boolean (e.g. markedAsType). 
These are small but mighty fixes to push to prod asap

Small fixes

---

.github/workflows/.trivyignore
pom.xml
src/main/java/eu/dissco/core/handlemanager/properties/ApplicationProperties.java
src/main/java/eu/dissco/core/handlemanager/service/DoiService.java
src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
src/main/java/eu/dissco/core/handlemanager/service/PidNameGeneratorService.java
src/main/java/eu/dissco/core/handlemanager/service/PidService.java
src/test/java/eu/dissco/core/handlemanager/service/DoiServiceTest.java
src/test/java/eu/dissco/core/handlemanager/service/HandleServiceTest.java
src/test/java/eu/dissco/core/handlemanager/service/PidNameGeneratorServiceTest.java

Reverts DiSSCo/handle-manager#137

Revert "Manual PIDs"
